[project]
name = "home-nexus-ha-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "paho-mqtt>=2.1.0",
    "pydantic>=2.12.4",
    "pyyaml>=6.0.3",
    "uvicorn[standard]>=0.38.0",
]
