homeassistant:
  name: Home Nexus Demo
  latitude: 52.52
  longitude: 13.405
  elevation: 34
  unit_system: metric
  currency: EUR
  external_url: http://localhost:8123

# enable the built-in REST API (enabled by default)
api:


# load packages in /config/packages
packages: !include_dir_named packages

logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug